/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: main.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "main.pb-c.h"
void   rpcheader__init
                     (Rpcheader         *message)
{
  static Rpcheader init_value = RPCHEADER__INIT;
  *message = init_value;
}
size_t rpcheader__get_packed_size
                     (const Rpcheader *message)
{
  assert(message->base.descriptor == &rpcheader__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpcheader__pack
                     (const Rpcheader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpcheader__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpcheader__pack_to_buffer
                     (const Rpcheader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpcheader__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpcheader *
       rpcheader__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpcheader *)
     protobuf_c_message_unpack (&rpcheader__descriptor,
                                allocator, len, data);
}
void   rpcheader__free_unpacked
                     (Rpcheader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpcheader__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dmessage__init
                     (DMessage         *message)
{
  static DMessage init_value = DMESSAGE__INIT;
  *message = init_value;
}
size_t dmessage__get_packed_size
                     (const DMessage *message)
{
  assert(message->base.descriptor == &dmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dmessage__pack
                     (const DMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dmessage__pack_to_buffer
                     (const DMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DMessage *
       dmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DMessage *)
     protobuf_c_message_unpack (&dmessage__descriptor,
                                allocator, len, data);
}
void   dmessage__free_unpacked
                     (DMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpcheader__field_descriptors[1] =
{
  {
    "rpcreq",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Rpcheader, rpcreq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpcheader__field_indices_by_name[] = {
  0,   /* field[0] = rpcreq */
};
static const ProtobufCIntRange rpcheader__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpcheader__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpcheader",
  "Rpcheader",
  "Rpcheader",
  "",
  sizeof(Rpcheader),
  1,
  rpcheader__field_descriptors,
  rpcheader__field_indices_by_name,
  1,  rpcheader__number_ranges,
  (ProtobufCMessageInit) rpcheader__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dmessage__field_descriptors[3] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DMessage, header),
    &rpcheader__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DMessage, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DMessage, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dmessage__field_indices_by_name[] = {
  1,   /* field[1] = a */
  2,   /* field[2] = b */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange dmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DMessage",
  "DMessage",
  "DMessage",
  "",
  sizeof(DMessage),
  3,
  dmessage__field_descriptors,
  dmessage__field_indices_by_name,
  1,  dmessage__number_ranges,
  (ProtobufCMessageInit) dmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
