/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: main.proto */

#ifndef PROTOBUF_C_main_2eproto__INCLUDED
#define PROTOBUF_C_main_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Rpcheader Rpcheader;
typedef struct _DMessage DMessage;


/* --- enums --- */


/* --- messages --- */

struct  _Rpcheader
{
  ProtobufCMessage base;
  int32_t rpcreq;
};
#define RPCHEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpcheader__descriptor) \
    , 0 }


struct  _DMessage
{
  ProtobufCMessage base;
  Rpcheader *header;
  int32_t a;
  int32_t b;
};
#define DMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dmessage__descriptor) \
    , NULL, 0, 0 }


/* Rpcheader methods */
void   rpcheader__init
                     (Rpcheader         *message);
size_t rpcheader__get_packed_size
                     (const Rpcheader   *message);
size_t rpcheader__pack
                     (const Rpcheader   *message,
                      uint8_t             *out);
size_t rpcheader__pack_to_buffer
                     (const Rpcheader   *message,
                      ProtobufCBuffer     *buffer);
Rpcheader *
       rpcheader__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpcheader__free_unpacked
                     (Rpcheader *message,
                      ProtobufCAllocator *allocator);
/* DMessage methods */
void   dmessage__init
                     (DMessage         *message);
size_t dmessage__get_packed_size
                     (const DMessage   *message);
size_t dmessage__pack
                     (const DMessage   *message,
                      uint8_t             *out);
size_t dmessage__pack_to_buffer
                     (const DMessage   *message,
                      ProtobufCBuffer     *buffer);
DMessage *
       dmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dmessage__free_unpacked
                     (DMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Rpcheader_Closure)
                 (const Rpcheader *message,
                  void *closure_data);
typedef void (*DMessage_Closure)
                 (const DMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rpcheader__descriptor;
extern const ProtobufCMessageDescriptor dmessage__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_main_2eproto__INCLUDED */
